# Generated by Django 3.2.7 on 2021-09-12 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DName', models.CharField(max_length=400)),
                ('DIntake', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Roll_no', models.IntegerField()),
                ('SName', models.CharField(max_length=30)),
                ('Marks', models.FloatField()),
                ('SAddress', models.CharField(max_length=100)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Records.department')),
            ],
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LName', models.CharField(max_length=30)),
                ('Sal', models.FloatField()),
                ('Lsub', models.CharField(max_length=30)),
                ('department', models.ManyToManyField(to='Records.Department')),
            ],
        ),
    ]
